development:
  adapter: postgresql
  database: yumster_dev
  host: localhost
  username: chattj

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

## Commented out as Heroku takes care of production
#production:
#  adapter: postgresql
#  database: yumster_prod
